# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "sfpscogs-shiga_aws_demo"
user = "shiga"
authenticator = "SNOWFLAKE_JWT"
private_key_path = "~/.ssh/rsa_key.p8"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
